#!/usr/bin/env bash
# ============================================================================
# v2.2: Vault Stats — Dashboard metrics for the wiki
# ============================================================================
# Generates a quick health/growth dashboard at 06-Config/dashboard.md
# Run after compile-pass or standalone.
#
# Usage: VAULT_PATH="$HOME/MyVault" bash vault-stats.sh
# ============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

acquire_lock "vault-stats" || exit 1

DASHBOARD="$VAULT_PATH/06-Config/dashboard.md"
REPORT_DATE=$(date +%Y-%m-%d)

echo "# Wiki Dashboard — $REPORT_DATE" > "$DASHBOARD"
echo "" >> "$DASHBOARD"

# ═══════════════════════════════════════════════════════════
# VAULT SIZE
# ═══════════════════════════════════════════════════════════
entry_count=$(find "$VAULT_PATH/04-Wiki/entries" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
concept_count=$(find "$VAULT_PATH/04-Wiki/concepts" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
moc_count=$(find "$VAULT_PATH/04-Wiki/mocs" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
source_count=$(find "$VAULT_PATH/04-Wiki/sources" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
total_notes=$((entry_count + concept_count + moc_count + source_count))

cat >> "$DASHBOARD" << EOF
## Vault Size

| Type | Count |
|------|-------|
| Entries | $entry_count |
| Concepts | $concept_count |
| MoCs | $moc_count |
| Sources | $source_count |
| **Total** | **$total_notes** |

EOF

# ═══════════════════════════════════════════════════════════
# GROWTH (last 7 days)
# ═══════════════════════════════════════════════════════════
echo "## Growth (last 7 days)" >> "$DASHBOARD"
echo "" >> "$DASHBOARD"

cutoff_date=$(date -d "7 days ago" +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d 2>/dev/null || echo "")
if [ -n "$cutoff_date" ]; then
  recent_entries=0
  for entry in "$VAULT_PATH/04-Wiki/entries"/*.md; do
    [ -f "$entry" ] || continue
    entry_date=$(grep -m1 '^date_entry:' "$entry" 2>/dev/null | sed 's/^date_entry: *//' || true)
    if [ -n "$entry_date" ] && [[ "$entry_date" > "$cutoff_date" ]]; then
      recent_entries=$((recent_entries + 1))
    fi
  done
  echo "- New entries (7d): $recent_entries" >> "$DASHBOARD"
else
  echo "- Growth tracking: date command unavailable" >> "$DASHBOARD"
fi

# ═══════════════════════════════════════════════════════════
# REVIEW STATUS
# ═══════════════════════════════════════════════════════════
echo "" >> "$DASHBOARD"
echo "## Review Status" >> "$DASHBOARD"
echo "" >> "$DASHBOARD"

reviewed_count=0
unreviewed_count=0
for entry in "$VAULT_PATH/04-Wiki/entries"/*.md; do
  [ -f "$entry" ] || continue
  reviewed=$(grep -m1 '^reviewed:' "$entry" 2>/dev/null | sed 's/^reviewed: *//' | tr -d '[:space:]' || true)
  if [ -z "$reviewed" ] || [ "$reviewed" = "null" ] || [ "$reviewed" = "" ]; then
    unreviewed_count=$((unreviewed_count + 1))
  else
    reviewed_count=$((reviewed_count + 1))
  fi
done

cat >> "$DASHBOARD" << EOF
| Status | Count |
|--------|-------|
| Reviewed | $reviewed_count |
| Unreviewed | $unreviewed_count |

EOF

# ═══════════════════════════════════════════════════════════
# HEALTH INDICATORS (from lint data)
# ═══════════════════════════════════════════════════════════
echo "## Health" >> "$DASHBOARD"
echo "" >> "$DASHBOARD"

# Orphan check (quick)
orphan_count=0
if [ -d "$VAULT_PATH/04-Wiki/entries" ]; then
  for entry in "$VAULT_PATH/04-Wiki/entries"/*.md; do
    [ -f "$entry" ] || continue
    note_name=$(basename "$entry" .md)
    if ! grep -rF "[[$note_name]]" "$VAULT_PATH" --include="*.md" --exclude-dir=.git 2>/dev/null | grep -v "^$entry:" | grep -q .; then
      orphan_count=$((orphan_count + 1))
    fi
  done
fi

# Edges count
edge_count=0
if [ -f "$VAULT_PATH/06-Config/edges.tsv" ]; then
  edge_count=$(( $(wc -l < "$VAULT_PATH/06-Config/edges.tsv" | tr -d ' ') - 1 ))
  [ "$edge_count" -lt 0 ] 2>/dev/null && edge_count=0
fi

# Last ingest
last_ingest=$(grep -m1 '^\## \[.*\] ingest' "$VAULT_PATH/06-Config/log.md" 2>/dev/null | sed 's/## \[\(.*\)\].*/\1/' || echo "never")

cat >> "$DASHBOARD" << EOF
| Indicator | Status |
|-----------|--------|
| Orphaned entries | $orphan_count |
| Typed edges | $edge_count |
| Last ingest | $last_ingest |
| URL index size | $(wc -l < "$VAULT_PATH/06-Config/url-index.tsv" 2>/dev/null || echo 0) entries |

EOF

# ═══════════════════════════════════════════════════════════
# RECENT ACTIVITY (last 5 from log.md)
# ═══════════════════════════════════════════════════════════
echo "## Recent Activity" >> "$DASHBOARD"
echo "" >> "$DASHBOARD"
echo '```' >> "$DASHBOARD"
grep '^## \[' "$VAULT_PATH/06-Config/log.md" 2>/dev/null | tail -5 >> "$DASHBOARD"
echo '```' >> "$DASHBOARD"
echo "" >> "$DASHBOARD"
echo "*Generated by vault-stats.sh on $REPORT_DATE*" >> "$DASHBOARD"

echo "Dashboard written to $DASHBOARD"
echo "Summary: $total_notes total notes, $unreviewed_count unreviewed, $orphan_count orphans"

log "Vault stats generated: $total_notes notes, $unreviewed_count unreviewed, $orphan_count orphans"
